version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: gatsby-remark-relative-images
    versions:
    - 2.0.2
  - dependency-name: gatsby-plugin-postcss
    versions:
    - 3.7.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
  - dependency-name: gatsby-plugin-netlify-cms
    versions:
    - 4.10.0
