backend:
  name: git-gateway
  repo: ma-bourassa/les-recouvrements-de-sols-lavallee
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: promotions
    label: Promotions
    folder: src/pages/promotions
    create: true
    media_folder: "{{slug}}"
    public_folder: "{{slug}}"
    fields:
      - { name: title, label: Titre }
      - { name: description, label: Description, widget: markdown }
      - { name: photo, label: Photo, widget: image }
      - { name: url, label: Url, widget: string }

  - name: realisations
    label: "Réalisations"
    folder: "src/pages/realisations"
    create: true
    media_folder: "{{slug}}"
    public_folder: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: photos, label: Photos, widget: list, field: { name: image, label: Image, widget: image } }
