backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/uploads
public_folder: /uploads

collections:
  - name: realisations
    label: "Réalisations"
    folder: "content/realisations"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: images, label: Images, widget: list, field: { name: image, label: Image, widget: image } }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }

          - {
              label: Features,
              name: features,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Feature1,
                    name: feature1,
                    widget: object,
                    fields:
                      [
                        { label: title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                  {
                    label: Feature2,
                    name: feature2,
                    widget: object,
                    fields:
                      [
                        { label: title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                  {
                    label: Feature3,
                    name: feature3,
                    widget: object,
                    fields:
                      [
                        { label: title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Specialties,
              name: specialties,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                  {
                    label: Specialties,
                    name: specialties,
                    widget: list,
                    fields: [{ label: Specialty, name: specialty, widget: string }],
                  },
                ],
            }

      - file: "content/pages/products.md"
        label: "Produits"
        name: "products"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "products-page" }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
              label: Products,
              name: products,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                  { label: External links title, name: linksTitle, widget: string },
                  {
                    label: External links,
                    name: links,
                    widget: list,
                    fields:
                      [{ label: Product name, name: name, widget: string }, { label: Url, name: url, widget: string }],
                  },
                ],
            }

      - file: "content/pages/realisations.md"
        label: "Réalisations"
        name: "realisations"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "realisations-page" }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }

      - file: "content/pages/promotions.md"
        label: "Promotions"
        name: "promotions"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "promotions-page" }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Aucune promotion, name: emptyPromo, widget: string }
          - {
              label: Promotions,
              name: promotions,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Url, name: url, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }

      - file: "content/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page" }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: text }
          - { label: Téléphone, name: phone, widget: string }
          - { label: Zone de service, name: area, widget: text }
          - { label: Adresse, name: address, widget: text }
