---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Static pages
- type: document
  path: content/pages/index.md
  label: Accueil
- type: document
  path: content/pages/products.md
  label: Produits
- type: document
  path: content/pages/realisations.md
  label: Realisations
- type: document
  path: content/pages/promotions.md
  label: Promotions
- type: document
  path: content/pages/contact.md
  label: Contact
- type: heading
  label: Dynamic pages
- type: directory
  path: content/realisations
  label: Realisations
  create: documents
  match: "**/*"
  templates:
  - realisation
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry-preview
