---
label: Products
hide_body: true
fields:
- type: text
  name: templateKey
  label: templateKey
  hidden: true
  config:
    required: true
  default: products-page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: subtitle
  label: Subtitle
  config:
    required: true
- type: field_group_list
  name: products
  label: Products
  fields:
  - type: text
    name: title
    label: Title
    config:
      required: true
  - type: textarea
    name: description
    label: Description
    config:
      wysiwyg: true
      required: true
      schema:
        format: html
  - type: file
    name: image
    label: Image
  - type: text
    name: linksTitle
    label: Links title
  - type: field_group_list
    name: links
    label: Links
    fields:
    - type: text
      name: url
      label: Url
    - type: text
      name: name
      label: Name
pages:
- content/pages/products.md
