---
label: Produits
hide_body: true
fields:
- name: produits
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: true
    label: Title
  - name: description
    type: textarea
    default: ''
    config:
      required: true
      wysiwyg: false
      schema:
        format: markdown
    label: Description
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  - name: links
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: true
      label: Name
    - name: url
      type: text
      config:
        required: true
      label: Url
    config:
      min: 
      max: 
      labelField: 
    label: Links
  config:
    min: 1
    max: 
    labelField: 
  label: Produits
pages:
- content/produits/produits.md
