---
label: Products
hide_body: true
fields:
- type: text
  name: templateKey
  label: templateKey
  hidden: true
  config:
    required: true
  default: products-page
- type: text
  name: title
  label: title
  config:
    required: true
- type: textarea
  name: subtitle
  label: subtitle
  config:
    required: true
- type: field_group_list
  name: products
  label: products
  fields:
  - type: text
    name: title
    label: title
    config:
      required: true
  - type: textarea
    name: description
    label: description
    config:
      wysiwyg: false
      required: true
  - type: file
    name: image
    label: image
  - type: text
    name: linksTitle
    label: linksTitle
  - type: field_group_list
    name: links
    label: links
    fields:
    - type: text
      name: url
      label: url
    - type: text
      name: name
      label: name
