---
label: Produits
hide_body: true
fields:
- type: text
  name: templateKey
  label: templateKey
- type: text
  name: title
  label: title
- type: textarea
  name: subtitle
  label: subtitle
- type: field_group_list
  name: products
  label: products
  fields:
  - type: text
    name: title
    label: title
  - type: textarea
    name: description
    label: description
  - type: file
    name: image
    label: image
  - type: text
    name: linksTitle
    label: linksTitle
  - type: field_group_list
    name: links
    label: links
    fields:
    - type: text
      name: url
      label: url
    - type: text
      name: name
      label: name
